### ISSUE TITLE
Interpolate `spriteFilePath`

### ISSUE THREAD

**Issue by patrikholcak** [vadymshymko/svg-sprite-generation-loader#109]
**Is your feature request related to a problem? Please describe.**
I need the symbol names to stay consistent between builds, but can change the sprite name itself. Can add it myself, if you’re interested

**Describe the solution you'd like**
Allow specifying `spriteFilePath: 'icons.[contenthash:8].svg'` 

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by vadymshymko** [comment]
@patrikholcak now you can use v2.2.0

**Comment by patrikholcak** [comment]
Amazing!
