### ISSUE TITLE
Enabling `filesystem` cache doesn’t output svg when cache is used

### ISSUE THREAD

**Issue by patrikholcak** [vadymshymko/svg-sprite-generation-loader#111]
**Describe the bug**
Enabling `filesystem` cache breaks the plugin (https://webpack.js.org/configuration/cache/). First run is OK but the second one doesn’t output anything.

First run
```
asset sprite.svg 829 bytes [emitted]
modules by path
  modules by path ./icons/ 191 bytes
    ./icons/icon1.svg 100 bytes [built] [code generated]
    ./icons/blogs/icon2.svg 91 bytes [built] [code generated]
```

Second run — not even output to the console

**To Reproduce**
1. Add `cache: { type: 'filesystem', }` to your webpack config
2. Run build
3. Icons are correctly compiled
4. Re-run build again
5. Icons aren’t compiled

**Expected behavior**
Icons compile when cache is used

**Additional context**
All other svg sprite loaders I tried also suffer from this issue, so not sure how fixable this is.

**Comment by vadymshymko** [comment]
@patrikholcak Hi. Thank you for your feedback. Please try version 2.2.1.

**Comment by patrikholcak** [comment]
You are on fire mate 🔥
